### ISSUE TITLE
Cannot stop log/pact.log from being created

### ISSUE THREAD

**Issue by BenSayers** [bethesque/pact-mock_service#15]
I'm starting the pact mock service using this command:
```
pact-mock-service --port 1234 --log build-output/pact-mock-service-logs/pact.log --cors --pact-dir build-output/pact
```

Despite the fact I am passing a specific log file the file `log/pact.log` is created with the following contents:
```
# Logfile created on 2015-03-03 00:22:16 +1100 by logger.rb/31641
```

If I'm doing it wrong please let me know. Otherwise I think this is a bug.

I am using pact-mock_service 0.4.1, Ruby 1.9.3p551 and OS X 10.10.2.

**Comment by bethesque** [comment]
It does sound like a bug. Are the actual logs going to the one you specify?

**Comment by BenSayers** [comment]
Yes

**Comment by bethesque** [comment]
I've fixed it, but it's not worth doing a release just for this. It will be out in the next release.
