### ISSUE TITLE
Support for 'Pact::ArrayLike'

### ISSUE THREAD

**Issue by michaelisgro** [bethesque/pact-mock_service#26]
'Pact::ArrayLike' doesn't seem to work, is there support for [flexible array matching] (https://github.com/realestate-com-au/pact/wiki/v2-flexible-matching)?

An example:
{
   'json_class': 'Pact::ArrayLike',
   'contents': {colour: 'red'},
   'min': 2
}

**Comment by bethesque** [comment]
What version of what code are you using?
