### ISSUE TITLE
interactions with query parameters embedded directly in the URL are considered non-matching

### ISSUE THREAD

**Issue by timoreimann** [bethesque/pact-mock_service#29]
Setting up an interaction using a `withRequest` component as in

```javascript
myProvider.withRequest({
    method: "get",
    path: "/resource?query=param"
});
```

leads to a _No matching interaction found for GET /resource?query=param_ error on the mock service end.

However, if I split out the query parameter into a dedicated `query` property as in

```javascript
myProvider.withRequest({
    method: "get",
    path: "/resource",
    query: { query: "param" }
});
```

the interaction is matched successfully.

While it should probably be good practice to separate the path from the query parameter, I think that the mock service should still consider the interaction as matching in this case in order to avoid confusion on the user's end. This seems especially important when employing the more concise syntax

```javascript
myProvider.withRequest("get", "/resource?query=param")
```

where a separate object is not required to specify the request.

If making the mock service more flexible in this regards is not an option, then I'd suggest to at least improve the error message because the current one makes it fairly hard to see what the problem is.

**Comment by bethesque** [comment]
It looks like you're using the javascript DSL. This would be handled by the javascript side, not the mock server - if you'd like to submit a PR to the javascript DSL to do this, I'd be happy to accept it.

**Comment by timoreimann** [comment]
@bethesque, sorry for not mentioning the fact that I am using the JS DSL. Will close this ticket a create another one in the correct repository.

**Comment by timoreimann** [comment]
Done: https://github.com/DiUS/pact-consumer-js-dsl/issues/48
