### ISSUE TITLE
Not able to create an interaction

### ISSUE THREAD

**Issue by yadavsaroj** [bethesque/pact-mock_service#31]
Hi,

We have clients in different languages so I want to use pact-mock_service via HTTP directly. I tried to create an interaction via curl but does not seem to be working. Am I missing something here? I tried to trace what [pact ruby client](https://github.com/realestate-com-au/pact) passes in and it seems to match what I am doing below.

here is my request - 
```
curl -H "Content-Type: application/json" -X POST -d "{\"description\":\"a request for an account\",\"provider_state\":\"an account exists\",\"request\":{\"method\":\"get\",\"path\":\"/accounts/1\",\"query\":\"include_deleted=false&include_locked=false\"},\"response\":{\"status\":200,\"headers\":{\"Content-Type\":\"application/json\"},\"body\":{\"id\":1,\"is_active\":true,\"name\":\"Test account\",\"subdomain\":\"supercool\",\"time_zone\":\"UTC\",\"created_at\":null,\"owner_id\":null,\"host_mapping\":null,\"updated_at\":null,\"locale_id\":5,\"sandbox_master_id\":null,\"is_serviceable\":true,\"help_desk_size\":\"1\",\"shard_id\":1,\"lock_state\":0,\"route_id\":null,\"deleted_at\":null,\"account_group_id\":1,\"dnsttl\":null}}}" localhost:5000/interactions
```
and the response - 

```
{"message":"No interaction found for POST /interactions","interaction_diffs":[]}
```

**Comment by bethesque** [comment]
Have a look at this example. I think you're missing the
X-Pact-Mock-Service header.

https://gist.github.com/bethesque/9d81f21d6f77650811f4


Regards,
Beth


On Tue, Nov 17, 2015 at 11:22 AM, Saroj Yadav <notifications@github.com>
wrote:

> Hi,
>
> We have clients in different languages so I want to use pact-mock_service
> via HTTP directly. I tried to create an interaction via curl but does not
> seem to be working. Am I missing something here? I tried to trace what pact
> ruby client <https://github.com/realestate-com-au/pact> passes in and it
> seems to match what I am doing below.
>
> here is my request -
>
> curl -H "Content-Type: application/json" -X POST -d "{\"description\":\"a request for an account\",\"provider_state\":\"an account exists\",\"request\":{\"method\":\"get\",\"path\":\"/accounts/1\",\"query\":\"include_deleted=false&include_locked=false\"},\"response\":{\"status\":200,\"headers\":{\"Content-Type\":\"application/json\"},\"body\":{\"id\":1,\"is_active\":true,\"name\":\"Test account\",\"subdomain\":\"supercool\",\"time_zone\":\"UTC\",\"created_at\":null,\"owner_id\":null,\"host_mapping\":null,\"updated_at\":null,\"locale_id\":5,\"sandbox_master_id\":null,\"is_serviceable\":true,\"help_desk_size\":\"1\",\"shard_id\":1,\"lock_state\":0,\"route_id\":null,\"deleted_at\":null,\"account_group_id\":1,\"dnsttl\":null}}}" localhost:5000/interactions
>
> and the response -
>
> {"message":"No interaction found for POST /interactions","interaction_diffs":[]}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bethesque/pact-mock_service/issues/31>.
>



-- 
Bethany Skurrie
Software Developer

DiUS Computing Pty. Ltd.


*where ideas are engineered *Phone: +61 3 9008 5400
Mobile: +61 415 413 713

www.dius.com.au

This email is intended solely for the use of the addressee and may contain
information that is confidential or privileged. If you receive this email
in error please notify the sender and delete the email immediately.

**Comment by yadavsaroj** [comment]
Ah! Thanks. 

BTW we at Zendesk are thinking of using pact, pact-mock_service and related libraries in 2 ways - 

1. For contract testing between service (e.g. an account service) and its client in different languages. A client creates a contract and the service verifies it.

2. For testing of an app which uses a service client to talk to the service. e.g. Ruby apps use account service client in ruby to talk to the account service. Similarly Scala apps use account service client in Scala to talk to the account service. This is how we are planning to use pact-mock_service - 

  1. When the app boots up in test environment, all the interactions created in step 1 are replayed against the mock service. This lets us use interactions as fixtures when testing apps which use services. 

  1. During testing, the service client talks to the mock service (pact-mock_service) instead of a real service. 

  1. Apps using the client are agnostic whether client talks to mock service or real service.

What do you think? Really appreciate your feedback.

**Comment by bethesque** [comment]
The pact-support mailing list would be a good place to ask this question.

You'll want to use the most flexible matching for the requests if you're using it to run applications against with a real user, not just known test fixtures. Pact isn't really designed to be used this way, so it might work, but it might not be super straightforward! Give it a go though, it can't hurt.

**Comment by Alankritham** [comment]
What is the issue with this piece of code:

beforeEach((done) => {
     //start the mock server
     provider.setup().then(() => {
       console.log('YES SETUP')
     }).then(() => {done()})

     const someinteraction = {
       state: ' I have list of cards',
       uponReceiving: 'A request of cards',
       withRequest: {
         method: 'POST',
         path: 'card',
         headers:{
           'Accept':'application/json'
         }
       },
       willRespondWith: {
         status:200,
         headers: {
           'Content-Type': 'application/json'
         },
         body: EXPECTED_BODY
       }
     }
     return provider.addInteraction(someinteraction)
  })


I am unable to create a interaction. It gives me the following error:
console.error node_modules/jest-jasmine2/build/jasmine/Env.js:161
      PopsicleError: Unable to connect to "http://127.0.0.1:2202/pact"
      Caused by: Error: connect ECONNREFUSED 127.0.0.1:2202
          at Request.Object.<anonymous>.Request.error (//node_modules/popsicle/src/request.ts:91:12)
          at ClientRequest.<anonymous> (//node_modules/popsicle/src/index.ts:218:31)
          at emitOne (events.js:116:13)
          at ClientRequest.emit (events.js:211:7)
          at Socket.socketErrorListener (_http_client.js:387:9)
          at emitOne (events.js:116:13)
          at Socket.emit (events.js:211:7)
          at emitErrorNT (internal/streams/destroy.js:64:8)
          at _combinedTickCallback (internal/process/next_tick.js:138:11)
          at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by bethesque** [comment]
@Alankritham you'll need to ask this in the pact js support forums. Have you looked at the examples in the pact js project?
