### ISSUE TITLE
Accepting the entire pact file instead of interactions

### ISSUE THREAD

**Issue by guyisra** [bethesque/pact-mock_service#50]
Currently, I need the pact-mock_service to run as a service, and I am doing (in ruby)

```
system "pact-mock-service start -p #{PACT_PORT} -l pact/pact.log"
sleep 2
# `curl -XDELETE -H "X-Pact-Mock-Service: true" localhost:#{PACT_PORT}/interactions`

pact = JSON.parse(File.read('pactfile.json'))
pact['interactions'].each do |interaction|
  `curl -XPOST -H "X-Pact-Mock-Service: true" -H "Content-Type: application/json" http://localhost:#{PACT_PORT}/interactions -d '#{interaction.to_json}'`
end
```

Is there a way to avoid splitting the interactions, and just send the mock service the entire pactfile and let it parse the interactions from it? That way it won't require ruby to parse the interactions

**Comment by bethesque** [comment]
Hi Guy,

Sort of. There is a PUT to /interactions, however, the format it takes is
not exactly the pact file format. It expects the Pact terms and
SomethingLikes to be encoded in a Ruby specific way, not the v2+ encoding.
So it will work only if you have none of these. But in fact, the code you
have written above has the same problem.

https://github.com/bethesque/pact-mock_service/blob/master/lib/pact/mock_service/request_handlers/interactions_put.rb

Beth
