### ISSUE TITLE
Path matcher does not generate correct pact file

### ISSUE THREAD

**Issue by andrewspinks** [bethesque/pact-mock_service#55]
Using a path matcher seems to work correctly from the consumer point of view, but the matcher details are missing from the outputted pact file.

The interaction sent to the mock server:
```
{
  "description": "a request for an alligator with path matcher",
  "provider_state": "an alligator exists",
  "request": {
    "method": "get",
    "path": {
      "json_class": "Pact::Term",
      "data": {
        "generate": "/alligators/1234",
        "matcher": {"json_class":"Regexp","o":0,"s":"^\\/alligators\\/[0-9]{4}"}
      }
    }
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "application/json"
    },
    "body": {
      "type": "alligator",
      "name": "Mary"
    }
  }
}
```

And the resulting pact file:
```
{
      "description": "a request for an alligator with path matcher",
      "provider_state": "an alligator exists",
      "request": {
        "method": "get",
        "path": "/alligators/1234"
      },
      "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json"
        },
        "body": {
          "type": "alligator",
          "name": "Mary"
        }
      }
    }
```

This is probably related to #11

**Comment by bethesque** [comment]
Yup, that's because it's not needed on the provider side. You need a concrete path when verifying on the provider side. The matcher is only relevant for the consumer side matching.

**Comment by andrewspinks** [comment]
OK, thanks for the clarification Beth. Let me go back to trying to understand the use case for using a path matcher...

**Comment by mefellows** [comment]
For posterity, as I understand it, the path matcher is useful on the consumer side where dynamic values might be created from the collaborating client code, perhaps without control over the resources it wants to access e.g. `GET /users/1234` or `GET /articles/<todays date>` etc. As Beth explains, this is only relevant on the consumer side and thus is not required to be in the pact file itself.

**Comment by bethesque** [comment]
Yup.

```json

"path": {
      "json_class": "Pact::Term",
      "data": {
        "generate": "/alligators/1234",
        "matcher": {"json_class":"Regexp","o":0,"s":"^\\/alligators\\/[0-9]{4}"}
      }
    }
```

This code says: when I verify the request on the provider side, I want to use the path `/alligators/1234`, but in my consumer code, I want the mock service to respond to a request for any alligator with this response.
