### ISSUE TITLE
JSON dependency not downloading automatically when installing

### ISSUE THREAD

**Issue by mboudreau** [bethesque/pact-mock_service#8]
After installing ruby and gems, we run a simple `gem i pact-mock_service` which seems to download just fine and it's able to use the command, but it crashes since it's missing the json dependency. 

It doesn't seem to download it automatically or it simply fails silently since the json dependency needs the dev kit to be installed as well.

**Comment by bethesque** [comment]
Are you on windows?

**Comment by mboudreau** [comment]
I'm not, but other developers are :)

**Comment by bethesque** [comment]
json is a dependency in my Gemfile.lock, can you check yours?

```
    json (1.8.1)
...
    pact-support (0.1.3)
      awesome_print (~> 1.1)
      find_a_port (~> 1.0.1)
      json
      rack-test (~> 0.6.2)
      randexp (~> 0.1.7)
      rspec (>= 2.14)
      term-ansicolor (~> 1.0)
      thor
```

My workmate mentioned that he'd had problems with JSON on windows, and needed the dev-kit. He was using windows to create a standalone ruby executable for pact, and gave me these instructions to create it:

https://github.com/bethesque/pact-mock_service/wiki/Building-a-Windows-standalone-executable

See if that helps? I've never done Ruby on windows, so I'd just be googling the problem.

**Comment by mboudreau** [comment]
I can see that dependency too, but I think the issue is that it's failing
silently if you don't have the dev kit installed on windows.  Either way,
it's a bit confusing and we were scratching our heads as to why it wasn't
working.  It would be nice to have windows specific directions in the
readme file or a link to it.

For our purposes, we couldn't get it running on windows using ruby 2.x
without instability.  We also had to downgrade ruby gems to 2.0.3 to work
with native extensions, then had to install the dev kit manually to be able
to install json and get it working.  Here's part of our README for our
project on how to get it up and running.  Just for good measure, I added
the step of manually installing json so it doesn't silently fail.

```

You will also need to install Ruby 1.9.x ([windows install](
http://rubyinstaller.org/downloads/) with the appropriate Dev Kit (windows
only, on the same page as the ruby download) or `apt-get install
ruby1.9.3`) and [RubyGems](https://rubygems.org/pages/download).  After
Ruby has been installed, you must setup the DevKit; run the install package
and extract it wherever is needed, then run:

ruby dk.rb init
ruby dk.rb install

After the install of RubyGems, it must be downgraded to a previous version
for compatibility reasons (don't ask):

gem update --system 2.0.3
Finally, you can install the mock service for pact.  Run the following
command to install it globally:

gem i json pact-mock_service

```

Hope this helps.

**Comment by bethesque** [comment]
Good work. Sorry I couldn't be more help. You're probably the first people to run it on windows! Seeing as the wiki is open to everyone, would you like to add a wiki page called "Installing the pact-mock_service gem on Windows"?

**Comment by mboudreau** [comment]
Sure thing.

**Comment by bethesque** [comment]
Btw, are you interested in building executable, as per those instructions? If you send it to me, I can upload it to the releases page, and it should mean you don't have to do the whole Ruby setup again.

**Comment by mboudreau** [comment]
I'm sorry, I'm new to Ruby; does the gem automatically build the executable
for us?  Would it just be in the gems directory?

**Comment by mboudreau** [comment]
Wiki page added. I recommend you add a link to it from the README:
https://github.com/bethesque/pact-mock_service/wiki/Installing-the-pact-mock_service-gem-on-Windows

**Comment by bethesque** [comment]
Thank you! Done.

The gem does not automatically build an executable. The instructions I sent were how to build the executable, so that it packages Ruby and all the gems, and you don't have to install Ruby separately. One of my workmates did it, but I've lost the package, and I don't have a windows machine.

**Comment by mboudreau** [comment]
Gotcha. Gimme a moment to do that and I'll send you the package.

**Comment by mboudreau** [comment]
Alright, it's been packaged.  You can find pact.exe and pact-mock-service.exe on my google drive:

pact: https://drive.google.com/file/d/0B5HCBC5lmHhzc1BVbkYwZHM2UmM/view?usp=sharing
pact-mock-service: https://drive.google.com/file/d/0B5HCBC5lmHhzVGtLOUNpeUNCbVE/view?usp=sharing

Cheers and thanks for all the help.

**Comment by bethesque** [comment]
That's fantastic, I'll put them on the releases page, thanks so much.

**Comment by mboudreau** [comment]
No problem.  Thanks for the work on pact :)

I actually got pact running from within grunt for our e2e testing process.
I'll create another wiki page to explain the process.  Ruby has given us a
lot of issues with node though and I was thinking of maybe spending some
time creating a node version of the mock server to easier integration :)

**Comment by bethesque** [comment]
That has been considered often, however, it is a non-trivial amount of work.

**Comment by mboudreau** [comment]
I know, but I'm hoping that it would popularize pact even more :)

**Comment by bethesque** [comment]
Well, hope on the pact-dev channel and have a chat about it if you want to give it a go, and I'll point you to the specs and test cases.

**Comment by mboudreau** [comment]
Will do when I'm ready :)
